from __future__ import annotations

from dataclasses import dataclass, field

import pandas as pd


@dataclass(frozen=True)
class FeatureBuildResult:
    """Feature table plus names and metadata generated by a feature builder."""

    frame: pd.DataFrame
    feature_columns: list[str]
    metadata: pd.DataFrame = field(default_factory=pd.DataFrame)


def feature_metadata(features: list[str], group: str, source: str) -> pd.DataFrame:
    """Create a compact metadata table for generated features."""
    return pd.DataFrame(
        [{"feature": feature, "feature_group": group, "source": source} for feature in features]
    )
